# steps necessary.

# name

name: ci

# --------------------------------------------
# triggers
on: push

# --------------------------------------------
# doing the tests

# this is the basic format?
# jobs:
#   <job-id>:
#     runs-on: <runner>
#     steps:
#       - <step 1>
#       - <step 2>
#       - ...

jobs:
  # format
  formatter:
    runs-on: Ubuntu-24.04

    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci

      # ------ test --------

      - name: prettierversion
        run: npx prettier --version

      - name: Prettier
        run: npx prettier . --check

  # lint
  linter:
    runs-on: Ubuntu-24.04

    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci

      # ------- run test ----------
      - name: ESLint
        run: npx eslint .

  # tsc

  typecheck:
    runs-on: Ubuntu-24.04

    needs:
      - linter
      - formatter
    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci

      # ---------- tests --------
      - name: TypeScript type check
        run: npx tsc --noEmit

  # security tests
  security:
    needs: typecheck
    runs-on: Ubuntu-24.04

    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci

      # --------teststing-----

      # npm audit
      - name: npm audit
        run: npm audit --audit-level=high

      # # github's codeql
      # - uses: github/codeql-action/init@v3
      #   with:
      #     languages: javascript, typescript
      # - uses: github/codeql-action/analyze@v3

      # fix this up later. try to understand what the error is throwing.

      # secret scanning
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git

  # unit test
  unit-test:
    needs: security
    runs-on: Ubuntu-24.04

    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci

  # integration test
  integration-test:
    needs: unit-test
    runs-on: Ubuntu-24.04

    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci

  # full build test

  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    needs: integration-test

    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci

      # ------------ tests --------------
      - name: Build Next.js app
        run: npm run build

  # E2E test
  # not integrated

  E2E-test:
    needs: build-test
    runs-on: Ubuntu-24.04

    steps:
      # ------ setup ------
      # copies repository into machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # intsall node.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # install all dependencies.
      - name: Install dependencies
        run: npm ci
