#!/usr/bin/env node


// node:child_process is the built in module 
// we take execSync function from it.
const { execSync } = require("node:child_process");
// execSync allows you to run shell commands one after another. 
// "synchonously"


function run(cmd) {
    try {
        // first argument: command
        // second argument: writes out all of the command's results to terminal for programmer to see.
        execSync(cmd, {stdio: "inherit"});


    } catch (err) {
        console.error(`\n Hook failed while running: ${cmd}`);

        process.exit(1);
    }
}


function testRun(cmd){
    try {
        execSync(cmd, { stdio: "inherit" });
        return true;
    } catch {
        return false;
    }
  }



// begin logic.
console.log("Hello... starting your pre-commit checks.");


// prettier. 
console.log("checking formatting with prettier");

// check if styles okay.
const prettierOk = testRun("npx prettier --check .");
//applied to variable to be checked and then acted upon.

if (prettierOk){
    console.log("Your code is looking weird...");
    run("npx prettier --write .");
}
else{
    console.log("Your code is pretty!!!!");
}




// ESLint 
console.log("running ESLint");
run("npx eslint .");
console.log("Linting cleared!!");


// fine.
console.log("all pre-commit checks passed.");

// 0 means nothing wrong. 
// git listens to terminal before continuuing with the process. 
// if sees 0, continues. if sees 1, exits.
process.exit(0);