#!/usr/bin/env node




const { execSync } = require("node:child_process");



function run(cmd) {
    try {
        execSync(cmd, {stdio: "inherit"});


    } catch (err) {
        console.error(`\n Hook failed while running: ${cmd}`);

        process.exit(1);
    }
}




console.log("Type Checking!");
run("npx tsc --noEmit");



console.log("all types are clean.");